### ISSUE TITLE
@iconify-prerendered/vue-devicon does not have Django icon

### ISSUE THREAD

**Issue by hwmrocker** [cawa-93/iconify-prerendered#18]
I installed @iconify-prerendered/vue-devicon@0.23.1704871196 but I cant find the Django Icon, `IconDjangorest` is available but not for Django alone.

**Comment by cawa-93** [comment]
As I can see [devicon](https://icon-sets.iconify.design/devicon/) set doesn't contaibe "Django" icon. But  [devicon-plain ](https://icon-sets.iconify.design/devicon-plain/) - yes
