### ISSUE TITLE
[Request] Add Material Symbols outlined

### ISSUE THREAD

**Issue by matthew-dean** [cawa-93/iconify-prerendered#20]
Derp, I just realized I couldn't replace my Material Symbols icon font because I'm using the outline version. Can you add those, along with the different symbol weights?

Something like:

```ts
import { IconHelp } from '@iconify-prerendered/vue-material-symbols/400/outlined'
```

**Comment by cawa-93** [comment]
This set containse outlined version of all icons
![зображення](https://github.com/cawa-93/iconify-prerendered/assets/1662812/b81ae8f6-fe4c-4b03-b9a2-75afd062a06e)
